model:
  name: distilbert-base-uncased
comment: null
result_dir: results/distilbert-base-uncased

debug: false
seed: 20210425

train:
  SAM: false
  folds: 
    # - 1
    - 2
    - 3
    # - 4
    # - 5
  checkpoints: 
    # - null
    - results/distilbert-base-uncased/distilbert-base-uncased-focal-AdamW-lr1e-05_2.pth
    - results/distilbert-base-uncased/distilbert-base-uncased-focal-AdamW-lr1e-05_3.pth
    # - results/distilbert-base-uncased/distilbert-base-uncased-focal-AdamW-lr1e-05_4.pth
    # - null
  loss: 
    name: focal # ce, focal
    gamma: 2
    
  optimizer:
    name: AdamW # Adam, AdamW
  
  finetune:
    do: true
    step1_epochs: 2
    step2_epochs: 4
  max_epochs: 12
    
  lr: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    params:
      factor: 0.5
      patience: 3
      verbose: true
  
dataset:
  dir: data/ori
  ver: 1
  batch_size: 35
  num_workers: 8
