model:
  name: distilbert-base-uncased
comment: null
result_dir: results/distilbert-base-uncased

debug: false
seed: 20210425

train:
  SAM: false
  folds: 
    # - 1
    # - 2
    # - 3
    - 4
    # - 5
  checkpoints: 
    # - null
    # - null
    # - null
    - null
    # - null
  loss: 
    name: arcface # ce, focal, arcface
    params:
      gamma: 2.0
      s: 45.0
      m: 0.1
      crit: focal
    
  optimizer:
    name: AdamW # Adam, AdamW
  
  finetune:
    do: true
    step1_epochs: 3
    step2_epochs: 5
  max_epochs: 12
    
  lr: 0.00005
  scheduler:
    name: ReduceLROnPlateau
    params:
      factor: 0.5
      patience: 3
      verbose: true
  
dataset:
  dir: data/ori
  ver: 4
  batch_size: 35
  num_workers: 8
