model:
  name: squeezebert/squeezebert-uncased
comment: null
result_dir: results/squeezebert-uncased

debug: false
seed: 20210425

train:
  SAM: false
  folds: 
    - 1
    # - 2
    # - 3
    # - 4
    # - 5
  checkpoints: 
    - null
    # - null
    # - null
    # - null
    # - null
  loss: 
    name: focal # ce, focal
    gamma: 2
    
  optimizer:
    name: AdamW # Adam, AdamW
  
  finetune:
    do: true
    step1_epochs: 3
    step2_epochs: 5
  max_epochs: 10
    
  lr: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    params:
      factor: 0.5
      patience: 3
      verbose: true
  
dataset:
  dir: data/ori
  batch_size: 20
  num_workers: 8
